version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "./" # Location of package manifests
    schedule:
      interval: "monthly"

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "./server" # Location of package manifests
    schedule:
      interval: "monthly"


version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "./client" # Location of package manifests
    schedule:
      interval: "monthly"
