version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/server" 
    schedule:
      interval: "monthly"

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client" 
    schedule:
      interval: "monthly"
