version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "server" 
    schedule:
      interval: "weekly"

version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "client" 
    schedule:
      interval: "weekly"
