version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/server" 
    schedule:
      interval: "daily"

version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/client" 
    schedule:
      interval: "daily"
